const CFG=window.SWITCHCARE_CONFIG||{};
const SUPABASE_URL=String(CFG.SUPABASE_URL||"").trim().replace(/\/+$/,"");
const RAW_KEY=String(CFG.SUPABASE_PUBLISHABLE_KEY||CFG.SUPABASE_ANON_KEY||"").trim();
const KEY=RAW_KEY.replace(/^sb_publishable_sb_publishable_/,"sb_publishable_");
const CYCLE=Number(CFG.CYCLE_MONTHS||6),REMIND=Number(CFG.REMIND_DAYS||30);
const TOKEN_KEY="switchcare_session_v7";
let session=null,devices=[],auditRows=[],page="dashboard",busy=false;

const today=()=>new Date().toISOString().slice(0,10);
const fmt=d=>d?new Date(d+"T00:00:00").toLocaleDateString("zh-TW"):"-";
const addMonths=(d,m)=>{const x=new Date(d+"T00:00:00");x.setMonth(x.getMonth()+m);return x.toISOString().slice(0,10)};
const dayDiff=(a,b)=>Math.ceil((new Date(b+"T00:00:00")-new Date(a+"T00:00:00"))/86400000);
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const errText=e=>String(e?.message||e?.error_description||e||"未知錯誤");
const validKey=()=>KEY.startsWith("sb_publishable_");

function asciiSafe(v){
  const s=String(v??"");
  for(let i=0;i<s.length;i++){if(s.charCodeAt(i)>255)throw new Error("請求標頭出現非 Latin-1 字元，已阻止送出。")}
  return s;
}
async function rawFetch(path,options={}){
  const headers=new Headers();
  headers.set("apikey",asciiSafe(KEY));
  if(session?.access_token)headers.set("Authorization",asciiSafe("Bearer "+session.access_token));
  headers.set("Content-Type","application/json");
  headers.set("Accept","application/json");
  if(options.headers)for(const [k,v] of Object.entries(options.headers))headers.set(k,asciiSafe(v));
  const r=await fetch(SUPABASE_URL+path,{...options,headers});
  const text=await r.text();
  let body=null;try{body=text?JSON.parse(text):null}catch{body=text}
  if(!r.ok)throw new Error(body?.msg||body?.message||body?.error_description||body?.error||text||("HTTP "+r.status));
  return body;
}

async function boot(){
  if(!SUPABASE_URL||!KEY||!validKey()){renderSetup();return}
  try{
    const stored=sessionStorage.getItem(TOKEN_KEY)||localStorage.getItem(TOKEN_KEY);
    if(stored){try{session=JSON.parse(stored)}catch{session=null}}
    if(session?.access_token){renderLayout();await refresh();return}
    renderLogin();
  }catch(e){renderAuthError("初始化失敗："+errText(e))}
}
function persistSession(s){session=s;if(s)sessionStorage.setItem(TOKEN_KEY,JSON.stringify(s));else sessionStorage.removeItem(TOKEN_KEY)}
function renderSetup(){document.getElementById("app").innerHTML=`<div class="auth-wrap"><div class="auth-card"><h1>SWITCHCARE</h1><div class="sub">台電自動線路開關生命週期管理系統</div><div class="notice warning"><b>Supabase 設定不完整</b><br>請確認 config.js 已填入正確的 Project URL 與 <b>sb_publishable_...</b> Publishable Key。</div></div></div>`}
function renderAuthError(msg){document.getElementById("app").innerHTML=`<div class="auth-wrap"><div class="auth-card"><h1>SWITCHCARE</h1><div class="sub">系統初始化失敗</div><div class="auth-error" style="display:block">${esc(msg)}</div></div></div>`}
function renderLogin(){document.getElementById("app").innerHTML=`<div class="auth-wrap"><div class="auth-card"><h1>SWITCHCARE</h1><div class="sub">台電自動線路開關生命週期管理系統</div><label>Email</label><input id="loginEmail" type="email" autocomplete="username" value="" placeholder="Email"><label>密碼</label><input id="loginPassword" type="password" autocomplete="current-password" placeholder="密碼"><div id="loginError" class="auth-error" style="display:none"></div><button id="loginBtn" class="btn" type="button">登入系統</button></div></div>`;document.getElementById("loginBtn").onclick=signIn;document.getElementById("loginPassword").addEventListener("keydown",e=>{if(e.key==="Enter")signIn()})}
async function signIn(){
 const email=document.getElementById("loginEmail").value.trim(),password=document.getElementById("loginPassword").value,btn=document.getElementById("loginBtn");
 if(!email||!password)return showLoginError("請輸入 Email 與密碼。");
 btn.disabled=true;btn.textContent="登入中…";
 try{
   const body=await rawFetch("/auth/v1/token?grant_type=password",{method:"POST",headers:{"X-Client-Info":"switchcare-web-v7"},body:JSON.stringify({email,password})});
   if(!body?.access_token)throw new Error("Supabase 未回傳 access_token。");
   persistSession(body);renderLayout();await refresh();
 }catch(e){console.error(e);showLoginError("登入失敗："+errText(e))}
 finally{if(document.getElementById("loginBtn")){btn.disabled=false;btn.textContent="登入系統"}}
}
function showLoginError(m){const e=document.getElementById("loginError");if(e){e.textContent=m;e.style.display="block"}}
async function signOut(){try{if(session?.access_token)await rawFetch("/auth/v1/logout",{method:"POST"})}catch(e){}persistSession(null);devices=[];renderLogin()}
function nav(p,t){return `<button type="button" class="${page===p?"active":""}" onclick="go('${p}')">${t}</button>`}
function go(p){page=p;renderLayout();render()}
function pageTitle(){return ({dashboard:"充電管理總覽",switches:"開關設備主檔",charging:"充電與週期管理",usage:"領用／退庫管理",history:"生命週期紀錄",reports:"報表與稽核",settings:"系統設定"})[page]||"SwitchCare"}
function renderLayout(){document.getElementById("app").innerHTML=`<div class="app"><aside class="sidebar"><div class="brand">SWITCHCARE<br>台電自動線路開關管理系統<small>企業版｜生命週期・資料庫・稽核</small></div><nav class="nav">${nav("dashboard","儀表板")}${nav("switches","開關設備主檔")}${nav("charging","充電與週期管理")}${nav("usage","領用／退庫管理")}${nav("history","生命週期紀錄")}${nav("reports","報表與稽核")}${nav("settings","系統設定")}</nav></aside><main class="main"><div class="topbar"><div><h1>${pageTitle()}</h1><span class="muted">在庫計時・領用停止・退庫重新起算6個月</span></div><div style="display:flex;align-items:center;gap:10px">${page!=="settings"?`<button class="btn" type="button" onclick="openDevice()">＋ 新增開關</button>`:""}<span class="userbar">${esc(session?.user?.email||session?.email||"")}</span><button class="btn secondary small" type="button" onclick="signOut()">登出</button></div></div><div id="content"></div></main></div>`}
async function refresh(){try{const body=await rawFetch("/rest/v1/switches?select=*&order=taipower_no.asc",{method:"GET",headers:{"Accept-Profile":"public"}});devices=body||[];render()}catch(e){document.getElementById("content").innerHTML=`<div class="panel"><div class="notice danger"><b>資料庫查詢失敗</b><br>${esc(errText(e))}</div><div class="diagnostic">URL：${esc(SUPABASE_URL)}\nKey格式：${validKey()?"sb_publishable_ 正確":"錯誤"}\n使用者：${esc(session?.user?.email||session?.email||"")}</div></div>`}}
function statusOf(x){if(x.state==="領用中")return{label:"領用中",cls:"gray",days:null};if(x.state==="送檢充電")return{label:"送檢充電",cls:"info",days:null};if(x.state==="充電中")return{label:"充電中",cls:"info",days:null};if(!x.next_charge_date)return{label:"待建週期",cls:"gray",days:null};const d=dayDiff(today(),x.next_charge_date);return d<0?{label:"逾期",cls:"danger",days:d}:d<=REMIND?{label:"即將到期",cls:"warning",days:d}:{label:"正常",cls:"normal",days:d}}
function card(t,n,c=""){return `<div class="card ${c}"><div class="label">${t}</div><div class="num">${n}</div></div>`}
function deviceTable(list,showDays=false){return `<div class="table-wrap"><table><thead><tr><th>料號</th><th>台電編號</th><th>型式</th><th>評價</th><th>狀態</th><th>週期起算</th><th>下次充電</th><th>單號</th><th>操作</th></tr></thead><tbody>${list.map(x=>{const s=statusOf(x);return `<tr><td>${esc(x.material_no)}</td><td>${esc(x.taipower_no)}</td><td>${esc(x.type)}</td><td>${esc(x.rating_type)}</td><td><span class="badge ${s.cls}">${s.label}</span></td><td>${fmt(x.cycle_start_date)}</td><td>${fmt(x.next_charge_date)}${showDays&&s.days!==null?`<br><span class="muted">${s.days<0?"逾期 "+Math.abs(s.days)+" 天":"剩 "+s.days+" 天"}</span>`:""}</td><td>${esc(x.transfer_no||x.issue_no||"-")}</td><td><button class="btn small secondary" type="button" onclick="detail('${x.id}')">查看</button></td></tr>`}).join("")}</tbody></table></div>`}
function dashboard(){const stock=devices.filter(x=>x.state!=="領用中"),issued=devices.filter(x=>x.state==="領用中"),soon=stock.filter(x=>statusOf(x).label==="即將到期"),over=stock.filter(x=>statusOf(x).label==="逾期"),proc=devices.filter(x=>["送檢充電","充電中"].includes(x.state));document.getElementById("content").innerHTML=`<div class="cards">${card("設備總數",devices.length)}${card("目前在庫",stock.length,"success")}${card("領用中",issued.length)}${card("30天內到期",soon.length,"warning")}${card("逾期",over.length,"danger")}${card("送檢／充電",proc.length,"info")}</div><div class="panel"><h2>核心業務規則</h2><div class="kpi-mini"><div>在庫週期<b>6個月</b></div><div>提前預警<b>30天</b></div><div>領用期間<b>停止計時</b></div><div>退庫<b>重新起算6個月</b></div></div></div><div class="panel"><h2>逾期設備</h2>${over.length?deviceTable(over,true):'<div class="empty">目前沒有逾期設備</div>'}</div>`}
function switchesPage(){document.getElementById("content").innerHTML=`<div class="panel"><div class="toolbar"><input id="sq" placeholder="搜尋料號／台電編號／型式／單號" oninput="filterDevices()"><select id="ss" onchange="filterDevices()"><option value="">全部狀態</option><option>正常</option><option>即將到期</option><option>逾期</option><option>領用中</option><option>送檢充電</option><option>充電中</option></select><button class="btn secondary" type="button" onclick="exportCSV()">匯出CSV</button></div><div id="dt">${deviceTable(devices)}</div></div>`}
function filterDevices(){const q=(document.getElementById("sq").value||"").toLowerCase(),s=document.getElementById("ss").value;document.getElementById("dt").innerHTML=deviceTable(devices.filter(x=>(!q||[x.material_no,x.taipower_no,x.type,x.issue_no,x.transfer_no].join(" ").toLowerCase().includes(q))&&(!s||statusOf(x).label===s)))}
function chargingPage(){const l=devices.filter(x=>x.state!=="領用中"&&["即將到期","逾期","送檢充電","充電中"].includes(statusOf(x).label));document.getElementById("content").innerHTML=`<div class="notice">只有在庫設備計算6個月週期；領用停止；退庫重新起算。</div><div class="panel"><div class="toolbar"><button class="btn" type="button" onclick="batchSend()">批次送檢</button></div>${l.length?deviceTable(l,true):'<div class="empty">目前沒有需要處理的設備</div>'}</div>`}
function usagePage(){const i=devices.filter(x=>x.state==="領用中"),s=devices.filter(x=>x.state!=="領用中");document.getElementById("content").innerHTML=`<div class="notice">領用中的開關不需要充電倒數；退庫後視同剛入庫。</div><div class="panel"><h2>領用中（${i.length}）</h2>${i.length?deviceTable(i):'<div class="empty">目前沒有領用中的設備</div>'}</div><div class="panel"><div class="toolbar"><button class="btn" type="button" onclick="openUsage('issue',${JSON.stringify(s.map(x=>x.id))})">領用／出庫</button><button class="btn success" type="button" onclick="openUsage('return',${JSON.stringify(i.map(x=>x.id))})">退庫／重新入庫</button></div></div>`}
async function historyPage(){document.getElementById("content").innerHTML=`<div class="panel"><div class="toolbar"><input id="hq" placeholder="搜尋台電編號／料號／事件／單號" oninput="filterHistory()"></div><div id="ht"><div class="empty">載入中…</div></div></div>`;try{const h=await rawFetch("/rest/v1/audit_log?select=*&order=event_at.desc&limit=1000",{method:"GET",headers:{"Accept-Profile":"public"}});auditRows=h||[];renderHistoryRows(auditRows)}catch(e){document.getElementById("ht").innerHTML=`<div class="notice danger">${esc(errText(e))}</div>`}}
function renderHistoryRows(r){document.getElementById("ht").innerHTML=r.length?`<div class="table-wrap"><table><thead><tr><th>時間</th><th>事件</th><th>台電編號</th><th>料號</th><th>單號</th><th>操作者</th><th>備註</th></tr></thead><tbody>${r.map(x=>`<tr><td>${new Date(x.event_at).toLocaleString("zh-TW")}</td><td>${esc(x.event_type)}</td><td>${esc(x.taipower_no||"-")}</td><td>${esc(x.material_no||"-")}</td><td>${esc(x.document_no||"-")}</td><td>${esc(x.actor_email||"-")}</td><td>${esc(x.note||"-")}</td></tr>`).join("")}</tbody></table></div>`:'<div class="empty">尚無紀錄</div>'}
function filterHistory(){const q=(document.getElementById("hq").value||"").toLowerCase();renderHistoryRows(auditRows.filter(r=>[r.event_type,r.taipower_no,r.material_no,r.document_no,r.actor_email,r.note].join(" ").toLowerCase().includes(q)))}
function openDevice(x=null){const v=x||{material_no:"",taipower_no:"",type:"",rating_type:"新品",warehouse:"",location:"",entry_date:today(),remark:""};document.body.insertAdjacentHTML("beforeend",`<div class="modal" id="modal"><div class="modal-box"><div class="modal-head"><h2>${x?"編輯":"新增"}開關設備</h2><button class="close" type="button" onclick="closeModal()">×</button></div><div class="form form-grid"><div><label>開關料號（10位）*</label><input id="fm" maxlength="10" value="${esc(v.material_no)}"></div><div><label>台電編號 *</label><input id="ft" value="${esc(v.taipower_no)}"></div><div class="full"><label>型式 *</label><input id="fy" value="${esc(v.type)}"></div><div><label>評價類型</label><select id="fr"><option ${v.rating_type==="新品"?"selected":""}>新品</option><option ${v.rating_type==="舊品"?"selected":""}>舊品</option></select></div><div><label>入帳日期 *</label><input id="fe" type="date" value="${v.entry_date||today()}"></div><div><label>倉庫</label><input id="fw" value="${esc(v.warehouse||"")}"></div><div><label>儲位</label><input id="fl" value="${esc(v.location||"")}"></div><div class="full"><label>備註</label><textarea id="fn">${esc(v.remark||"")}</textarea></div></div><div id="formMsg" class="notice danger" style="display:none"></div><div class="page-actions"><button class="btn secondary" type="button" onclick="closeModal()">取消</button><button class="btn" id="saveDeviceBtn" type="button" onclick="saveDevice('${x?.id||""}')">儲存</button></div></div></div>`)}
async function saveDevice(id){if(busy)return;busy=true;const btn=document.getElementById("saveDeviceBtn");if(btn){btn.disabled=true;btn.textContent="儲存中…"}try{const m=document.getElementById("fm").value.trim(),t=document.getElementById("ft").value.trim(),type=document.getElementById("fy").value.trim(),e=document.getElementById("fe").value;if(!/^\d{10}$/.test(m))throw new Error("料號必須為10位數字。");if(!t||!type||!e)throw new Error("請完整填寫必填欄位。");const row={material_no:m,taipower_no:t,type,rating_type:document.getElementById("fr").value,warehouse:document.getElementById("fw").value.trim(),location:document.getElementById("fl").value.trim(),entry_date:e};let path="/rest/v1/switches",method="POST",body={...row,state:"在庫",cycle_start_date:e,next_charge_date:addMonths(e,CYCLE_MONTHS)};if(id){path+="/id=eq."+encodeURIComponent(id);method="PATCH";delete body.entry_date}else{body.remark=document.getElementById("fn").value.trim()}const res=await rawFetch(path,{method,headers:{"Prefer":"return=representation","Accept-Profile":"public","Content-Profile":"public"},body:JSON.stringify(body)});closeModal();await refresh()}catch(e){const msg=document.getElementById("formMsg");if(msg){msg.textContent="儲存失敗："+errText(e);msg.style.display="block"}}finally{busy=false;const b=document.getElementById("saveDeviceBtn");if(b){b.disabled=false;b.textContent="儲存"}}}
function openUsage(mode,ids){if(!ids.length)return alert("目前沒有可操作設備。");const l=ids.map(id=>devices.find(x=>x.id===id)).filter(Boolean);document.body.insertAdjacentHTML("beforeend",`<div class="modal" id="modal"><div class="modal-box"><div class="modal-head"><h2>${mode==="issue"?"領用／出庫":"退庫／重新入庫"}</h2><button class="close" type="button" onclick="closeModal()">×</button></div><div class="form-grid"><div class="full"><label>設備</label><select id="uid">${l.map(x=>`<option value="${x.id}">${esc(x.taipower_no)}｜${esc(x.material_no)}｜${esc(x.type)}</option>`).join("")}</select></div><div><label>日期 *</label><input id="ud" type="date" value="${today()}"></div><div><label>單號</label><input id="un"></div><div class="full"><label>備註</label><textarea id="unote"></textarea></div></div><div class="notice">${mode==="issue"?"領用後停止充電倒數。":"退庫後從退庫日重新起算6個月。"}</div><div id="usageMsg" class="notice danger" style="display:none"></div><div class="page-actions"><button class="btn secondary" type="button" onclick="closeModal()">取消</button><button class="btn" type="button" onclick="saveUsage('${mode}')">確認</button></div></div></div>`)}
async function saveUsage(mode){const id=document.getElementById("uid").value,d=document.getElementById("ud").value,no=document.getElementById("un").value.trim(),note=document.getElementById("unote").value.trim();try{const fn=mode==="issue"?"issue_switch":"return_switch";await rawFetch("/rest/v1/rpc/"+fn,{method:"POST",headers:{"Accept-Profile":"public"},body:JSON.stringify({p_switch_id:id,p_event_date:d,p_document_no:no||null,p_note:note||null})});closeModal();await refresh()}catch(e){const x=document.getElementById("usageMsg");if(x){x.textContent="操作失敗："+errText(e);x.style.display="block"}}}
function batchSend(){const l=devices.filter(x=>["逾期","即將到期"].includes(statusOf(x).label));if(!l.length)return alert("目前沒有可送檢設備。");const d=prompt("送檢日期 YYYY-MM-DD",today());if(!d)return;Promise.all(l.map(x=>rawFetch("/rest/v1/rpc/send_switch_for_charge",{method:"POST",headers:{"Accept-Profile":"public"},body:JSON.stringify({p_switch_id:x.id,p_event_date:d,p_transfer_no:null,p_note:"批次送檢"})}))).then(refresh).catch(e=>alert("批次送檢失敗："+errText(e)))}
function detail(id){const x=devices.find(z=>z.id===id);if(!x)return;const s=statusOf(x);document.body.insertAdjacentHTML("beforeend",`<div class="modal" id="modal"><div class="modal-box"><div class="modal-head"><h2>設備生命週期</h2><button class="close" type="button" onclick="closeModal()">×</button></div><div class="form-grid"><div><b>料號</b><br>${esc(x.material_no)}</div><div><b>台電編號</b><br>${esc(x.taipower_no)}</div><div class="full"><b>型式</b><br>${esc(x.type)}</div><div><b>評價</b><br>${esc(x.rating_type)}</div><div><b>狀態</b><br><span class="badge ${s.cls}">${s.label}</span></div><div><b>入帳日期</b><br>${fmt(x.entry_date)}</div><div><b>週期起算</b><br>${fmt(x.cycle_start_date)}</div><div><b>下次充電</b><br>${fmt(x.next_charge_date)}</div><div><b>倉庫／儲位</b><br>${esc(x.warehouse||"-")} / ${esc(x.location||"-")}</div></div><div class="page-actions"><button class="btn secondary" type="button" onclick="closeModal();openDevice(devices.find(z=>z.id==='${x.id}'))">編輯</button>${x.state==="在庫"&&["逾期","即將到期"].includes(s.label)?`<button class="btn" type="button" onclick="closeModal();openCharge('${x.id}')">送檢</button>`:""}${["送檢充電","充電中"].includes(x.state)?`<button class="btn success" type="button" onclick="closeModal();completeCharge('${x.id}')">完成充電</button>`:""}${x.state==="領用中"?`<button class="btn success" type="button" onclick="closeModal();openUsage('return',['${x.id}'])">退庫</button>`:`<button class="btn danger" type="button" onclick="closeModal();openUsage('issue',['${x.id}'])">領用／出庫</button>`}</div></div></div>`)}
function openCharge(id){document.body.insertAdjacentHTML("beforeend",`<div class="modal" id="modal"><div class="modal-box"><div class="modal-head"><h2>送檢充電</h2><button class="close" type="button" onclick="closeModal()">×</button></div><div class="form-grid"><div><label>送檢日期 *</label><input id="cd" type="date" value="${today()}"></div><div><label>充電移撥單號 *</label><input id="cn"></div><div class="full"><label>備註</label><textarea id="cnote"></textarea></div></div><div id="chargeMsg" class="notice danger" style="display:none"></div><div class="page-actions"><button class="btn secondary" type="button" onclick="closeModal()">取消</button><button class="btn" type="button" onclick="saveCharge('${id}')">確認</button></div></div></div>`)}
async function saveCharge(id){const d=document.getElementById("cd").value,no=document.getElementById("cn").value.trim(),note=document.getElementById("cnote").value.trim();if(!d||!no)return showChargeMsg("送檢日期與移撥單號不可空白。");try{await rawFetch("/rest/v1/rpc/send_switch_for_charge",{method:"POST",headers:{"Accept-Profile":"public"},body:JSON.stringify({p_switch_id:id,p_event_date:d,p_transfer_no:no,p_note:note||null})});closeModal();await refresh()}catch(e){showChargeMsg("送檢失敗："+errText(e))}}
function showChargeMsg(m){const e=document.getElementById("chargeMsg");if(e){e.textContent=m;e.style.display="block"}}
function completeCharge(id){document.body.insertAdjacentHTML("beforeend",`<div class="modal" id="modal"><div class="modal-box"><div class="modal-head"><h2>登錄充電完成</h2><button class="close" type="button" onclick="closeModal()">×</button></div><div class="form-grid"><div><label>實際完成充電日 *</label><input id="ccd" type="date" value="${today()}"></div><div><label>移撥單號</label><input id="ccn"></div><div class="full"><label>備註</label><textarea id="ccnote"></textarea></div></div><div class="notice">完成後重新以實際完成日計算6個月。</div><div id="completeMsg" class="notice danger" style="display:none"></div><div class="page-actions"><button class="btn secondary" type="button" onclick="closeModal()">取消</button><button class="btn success" type="button" onclick="finishCharge('${id}')">確認完成</button></div></div></div>`)}
async function finishCharge(id){const d=document.getElementById("ccd").value,no=document.getElementById("ccn").value.trim(),note=document.getElementById("ccnote").value.trim();if(!d)return showCompleteMsg("完成日期不可空白。");try{await rawFetch("/rest/v1/rpc/complete_switch_charge",{method:"POST",headers:{"Accept-Profile":"public"},body:JSON.stringify({p_switch_id:id,p_event_date:d,p_transfer_no:no||null,p_note:note||null})});closeModal();await refresh()}catch(e){showCompleteMsg("完成充電失敗："+errText(e))}}
function showCompleteMsg(m){const e=document.getElementById("completeMsg");if(e){e.textContent=m;e.style.display="block"}}
function reportsPage(){const s=devices.filter(x=>x.state!=="領用中"),o=s.filter(x=>statusOf(x).label==="逾期"),n=s.filter(x=>statusOf(x).label==="即將到期"),i=devices.filter(x=>x.state==="領用中");document.getElementById("content").innerHTML=`<div class="panel"><h2>報表中心</h2><div class="toolbar"><button class="btn" type="button" onclick="report('overdue')">逾期清冊</button><button class="btn secondary" type="button" onclick="report('soon')">30天到期清冊</button><button class="btn secondary" type="button" onclick="report('issued')">領用中清冊</button><button class="btn secondary" type="button" onclick="exportCSV()">設備主檔</button></div><p class="muted">在庫 ${s.length} 台；逾期 ${o.length} 台；30天內到期 ${n.length} 台；領用中 ${i.length} 台。</p></div>`}
function report(k){let h=[],r=[];if(k==="overdue"){h=["料號","台電編號","型式","下次充電","逾期天數"];r=devices.filter(x=>statusOf(x).label==="逾期").map(x=>[x.material_no,x.taipower_no,x.type,x.next_charge_date,Math.abs(statusOf(x).days)])}else if(k==="soon"){h=["料號","台電編號","型式","下次充電","剩餘天數"];r=devices.filter(x=>statusOf(x).label==="即將到期").map(x=>[x.material_no,x.taipower_no,x.type,x.next_charge_date,statusOf(x).days])}else{h=["料號","台電編號","型式","領用日期","單號"];r=devices.filter(x=>x.state==="領用中").map(x=>[x.material_no,x.taipower_no,x.type,x.issue_date,x.issue_no])}download(h,r,"SwitchCare_"+k+"_"+today()+".csv")}
function exportCSV(){download(["料號","型式","台電編號","評價","倉庫","儲位","入帳日期","狀態","週期起算日","上次充電","下次充電","領用日期","退庫日期","領用單號","充電移撥單號"],devices.map(x=>[x.material_no,x.type,x.taipower_no,x.rating_type,x.warehouse,x.location,x.entry_date,x.state,x.cycle_start_date,x.last_charge_date,x.next_charge_date,x.issue_date,x.return_date,x.issue_no,x.transfer_no]),"SwitchCare_設備主檔_"+today()+".csv")}
function download(h,r,n){const q=v=>`"${String(v??"").replace(/"/g,'""')}"`,csv="\uFEFF"+[h,...r].map(x=>x.map(q).join(",")).join("\r\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download=n;a.click()}
function settingsPage(){document.getElementById("content").innerHTML=`<div class="panel"><h2>連線診斷</h2><div class="diagnostic">Project URL：${esc(SUPABASE_URL)}
Key格式：${validKey()?"sb_publishable_ 正確":"錯誤"}
登入者：${esc(session?.user?.email||session?.email||"(未登入)")}</div><button class="btn secondary" type="button" onclick="testDB()">測試資料庫</button><div id="dbTest" class="muted" style="margin-top:10px"></div></div>`}
async function testDB(){const e=document.getElementById("dbTest");try{await rawFetch("/rest/v1/switches?select=id&limit=1",{method:"GET",headers:{"Accept-Profile":"public"}});e.textContent="資料庫連線成功，switches 可查詢。"}catch(x){e.textContent="失敗："+errText(x)}}
function render(){if(page==="dashboard")dashboard();else if(page==="switches")switchesPage();else if(page==="charging")chargingPage();else if(page==="usage")usagePage();else if(page==="history")historyPage();else if(page==="reports")reportsPage();else if(page==="settings")settingsPage()}
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});
document.addEventListener("click",e=>{if(e.target?.id==="modal")closeModal()});
boot();
