const cfg=window.SWITCHCARE_CONFIG||{};
const CYCLE=Number(cfg.CYCLE_MONTHS||6), REMIND=Number(cfg.REMIND_DAYS||30);
const hasDB=!!(cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY&&window.supabase);
const db=hasDB?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;
let page="dashboard", devices=[], loading=false;

const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random();
const today=()=>new Date().toISOString().slice(0,10);
const addMonths=(d,m)=>{const x=new Date(d+"T00:00:00");x.setMonth(x.getMonth()+m);return x.toISOString().slice(0,10)};
const days=(a,b)=>Math.ceil((new Date(b+"T00:00:00")-new Date(a+"T00:00:00"))/86400000);
const fmt=d=>d?new Date(d+"T00:00:00").toLocaleDateString("zh-TW"):"-";
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));

async function boot(){
  renderLayout();
  if(!hasDB){document.getElementById("content").innerHTML=`<div class="panel"><div class="notice warning"><b>尚未連接正式資料庫</b><br>請先在 config.js 填入 Supabase Project URL 與 anon/public key。<br>目前不會把資料寫入瀏覽器 LocalStorage，避免誤以為已達永久保存標準。</div><h2>系統已就緒</h2><p class="muted">完成 Supabase 設定並執行 database/schema.sql 後，即可使用正式資料庫模式。</p></div>`;return}
  await refresh();
}
async function refresh(){loading=true;try{let q=db.from("switches").select("*").order("taipower_no");let {data,error}=await q;if(error)throw error;devices=data||[];}catch(e){console.error(e);alert("資料庫連線或查詢失敗："+e.message)}finally{loading=false;render()}}
function nav(p,t){return `<button class="${page===p?"active":""}" onclick="go('${p}')">${t}</button>`}
function go(p){page=p;renderLayout();render()}
function title(){return {dashboard:"充電管理總覽",switches:"開關設備主檔",charging:"充電與週期管理",usage:"領用／退庫管理",history:"生命週期紀錄",reports:"報表與稽核",settings:"系統設定"}[page]}
function renderLayout(){document.getElementById("app").innerHTML=`<div class="app"><aside class="sidebar"><div class="brand">SWITCHCARE<br>台電自動線路開關管理系統<small>企業版｜生命週期・永久資料庫・稽核</small></div><nav class="nav">${nav("dashboard","儀表板")}${nav("switches","開關設備主檔")}${nav("charging","充電與週期管理")}${nav("usage","領用／退庫管理")}${nav("history","生命週期紀錄")}${nav("reports","報表與稽核")}${nav("settings","系統設定")}</nav></aside><main class="main"><div class="topbar"><div><h1>${title()}</h1><span class="muted">領用停止計時・退庫重新起算6個月・資料庫永久保存</span></div>${page!=="settings"?`<button class="btn" onclick="openDevice()">＋ 新增開關</button>`:""}</div><div id="content"></div></main></div>`}
function st(x){if(x.state==="領用中")return{label:"領用中",cls:"gray",days:null};if(["送檢充電","充電中"].includes(x.state))return{label:x.state,cls:"info",days:null};if(!x.next_charge_date)return{label:"待建週期",cls:"gray",days:null};const d=days(today(),x.next_charge_date);return d<0?{label:"逾期",cls:"danger",days:d}:d<=REMIND?{label:"即將到期",cls:"warning",days:d}:{label:"正常",cls:"normal",days:d}}
function card(t,n,c=""){return `<div class="card ${c}"><div class="label">${t}</div><div class="num">${n}</div></div>`}
function table(list,showDays=false){return `<div class="table-wrap"><table><thead><tr><th>料號</th><th>台電編號</th><th>型式</th><th>評價</th><th>狀態</th><th>週期起算</th><th>下次充電</th><th>單號</th><th>操作</th></tr></thead><tbody>${list.map(x=>{const s=st(x);return `<tr><td>${esc(x.material_no)}</td><td>${esc(x.taipower_no)}</td><td>${esc(x.type)}</td><td>${esc(x.rating_type)}</td><td><span class="badge ${s.cls}">${s.label}</span></td><td>${fmt(x.cycle_start_date)}</td><td>${fmt(x.next_charge_date)}${showDays&&s.days!==null?`<br><span class="muted">${s.days<0?"逾期 "+Math.abs(s.days)+" 天":"剩 "+s.days+" 天"}</span>`:""}</td><td>${esc(x.transfer_no||x.issue_no||"-")}</td><td><button class="btn small secondary" onclick="detail('${x.id}')">查看</button></td></tr>`}).join("")}</tbody></table></div>`}
function render(){if(!document.getElementById("content"))return;switch(page){case"dashboard":dashboard();break;case"switches":switches();break;case"charging":charging();break;case"usage":usage();break;case"history":historyPage();break;case"reports":reports();break;case"settings":settings();break}}
function dashboard(){const stock=devices.filter(x=>x.state!=="領用中"),issued=devices.filter(x=>x.state==="領用中"),soon=stock.filter(x=>st(x).label==="即將到期"),over=stock.filter(x=>st(x).label==="逾期"),proc=devices.filter(x=>["送檢充電","充電中"].includes(x.state));document.getElementById("content").innerHTML=`<div class="cards">${card("設備總數",devices.length)}${card("目前在庫",stock.length,"success")}${card("領用中",issued.length)}${card("30天內到期",soon.length,"warning")}${card("逾期",over.length,"danger")}${card("送檢／充電",proc.length,"info")}</div><div class="panel"><h2>核心業務規則</h2><div class="notice">在庫才計算6個月週期；領用後停止計時；退庫視同重新入庫；充電完成後重新建立6個月週期。所有事件寫入資料庫歷史紀錄。</div></div><div class="panel"><h2>逾期設備</h2>${over.length?table(over,true):'<div class="empty">目前沒有逾期設備</div>'}</div>`}
function switches(){document.getElementById("content").innerHTML=`<div class="panel"><div class="toolbar"><input id="sq" placeholder="搜尋料號／台電編號／型式／單號" oninput="filterDevices()"><select id="ss" onchange="filterDevices()"><option value="">全部狀態</option><option>正常</option><option>即將到期</option><option>逾期</option><option>領用中</option><option>送檢充電</option><option>充電中</option></select><button class="btn secondary" onclick="openDevice()">新增</button><button class="btn secondary" onclick="exportCSV()">匯出CSV</button></div><div id="dt">${table(devices)}</div></div>`}
function filterDevices(){const q=(document.getElementById("sq").value||"").toLowerCase(),s=document.getElementById("ss").value;const list=devices.filter(x=>(!q||[x.material_no,x.taipower_no,x.type,x.issue_no,x.transfer_no].join(" ").toLowerCase().includes(q))&&(!s||st(x).label===s));document.getElementById("dt").innerHTML=table(list)}
function charging(){const list=devices.filter(x=>x.state!=="領用中"&&["即將到期","逾期","送檢充電","充電中"].includes(st(x).label));document.getElementById("content").innerHTML=`<div class="notice">領用中的設備不進行充電倒數。退庫後從退庫日重新起算6個月。</div><div class="panel"><div class="toolbar"><button class="btn" onclick="batchSend()">批次送檢</button></div>${list.length?table(list,true):'<div class="empty">目前沒有需要處理的在庫設備</div>'}</div>`}
function usage(){const issued=devices.filter(x=>x.state==="領用中"),stock=devices.filter(x=>x.state!=="領用中");document.getElementById("content").innerHTML=`<div class="notice">領用後停止充電計時；退庫後視同重新入庫，退庫日就是新的週期起算日。</div><div class="panel"><h2>目前領用中（${issued.length}）</h2>${issued.length?table(issued):'<div class="empty">目前沒有領用中的設備</div>'}</div><div class="panel"><div class="toolbar"><button class="btn" onclick="openUsage('issue',${JSON.stringify(stock.map(x=>x.id))})">領用／出庫</button><button class="btn success" onclick="openUsage('return',${JSON.stringify(issued.map(x=>x.id))})">退庫／重新入庫</button></div></div>`}
function historyPage(){db?document.getElementById("content").innerHTML=`<div class="panel"><div class="toolbar"><input id="hq" placeholder="搜尋台電編號／料號／事件／單號" oninput="filterHistory()"></div><div id="ht"><div class="empty">載入中...</div></div></div>`:document.getElementById("content").innerHTML='<div class="panel"><div class="empty">請先設定資料庫</div></div>';if(db)loadHistory()}
async function loadHistory(){const {data,error}=await db.from("audit_log").select("*").order("event_at",{ascending:false}).limit(500);if(error){document.getElementById("ht").innerHTML='<div class="notice danger">'+esc(error.message)+'</div>';return}window.auditRows=data||[];renderHistoryRows(window.auditRows)}
function renderHistoryRows(rows){document.getElementById("ht").innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr><th>時間</th><th>事件</th><th>設備</th><th>料號</th><th>單號</th><th>操作者</th><th>說明</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${new Date(r.event_at).toLocaleString("zh-TW")}</td><td>${esc(r.event_type)}</td><td>${esc(r.taipower_no||"-")}</td><td>${esc(r.material_no||"-")}</td><td>${esc(r.document_no||"-")}</td><td>${esc(r.actor_email||"system")}</td><td>${esc(r.note||"")}</td></tr>`).join("")}</tbody></table></div>`:'<div class="empty">沒有歷史紀錄</div>'}
function filterHistory(){const q=(document.getElementById("hq").value||"").toLowerCase();renderHistoryRows((window.auditRows||[]).filter(r=>[r.event_type,r.taipower_no,r.material_no,r.document_no,r.actor_email,r.note].join(" ").toLowerCase().includes(q)))}
function reports(){const stock=devices.filter(x=>x.state!=="領用中"),over=stock.filter(x=>st(x).label==="逾期"),soon=stock.filter(x=>st(x).label==="即將到期"),issued=devices.filter(x=>x.state==="領用中");document.getElementById("content").innerHTML=`<div class="panel"><h2>報表中心</h2><div class="toolbar"><button class="btn" onclick="report('overdue')">逾期清冊</button><button class="btn secondary" onclick="report('soon')">30天到期清冊</button><button class="btn secondary" onclick="report('issued')">領用中清冊</button><button class="btn secondary" onclick="exportCSV()">設備主檔</button></div><p class="muted">在庫 ${stock.length}；逾期 ${over.length}；30天內到期 ${soon.length}；領用中 ${issued.length}。</p></div>`}
function settings(){document.getElementById("content").innerHTML=`<div class="panel"><h2>資料庫連線狀態</h2><p class="${hasDB?"db-ok":"db-bad"}"><b>${hasDB?"已設定 Supabase":"尚未設定 Supabase"}</b></p><div class="settings">URL：${esc(cfg.SUPABASE_URL||"(空白)")}</div><p class="muted">只可使用 anon/public key。請勿將 service_role key 放進前端或 GitHub。</p></div><div class="panel"><h2>永久保存架構</h2><p>主資料：PostgreSQL；事件紀錄：audit_log；停用採狀態化，不直接刪除歷史；RLS 控制資料存取。</p></div>`}
function openDevice(x=null){const v=x||{material_no:"",type:"",taipower_no:"",rating_type:"新品",warehouse:"",location:"",entry_date:today(),remark:""};document.body.insertAdjacentHTML("beforeend",`<div class="modal" id="modal"><div class="modal-box"><div class="modal-head"><h2>${x?"編輯":"新增"}設備</h2><button class="close" onclick="closeModal()">×</button></div><div class="form form-grid"><div><label>開關料號（10位）*</label><input id="fm" maxlength="10" value="${esc(v.material_no)}"></div><div><label>台電編號 *</label><input id="ft" value="${esc(v.taipower_no)}"></div><div class="full"><label>型式 *</label><input id="fy" value="${esc(v.type)}"></div><div><label>評價類型</label><select id="fr"><option ${v.rating_type==="新品"?"selected":""}>新品</option><option ${v.rating_type==="舊品"?"selected":""}>舊品</option></select></div><div><label>入帳日期 *</label><input id="fe" type="date" value="${v.entry_date||today()}"></div><div><label>倉庫</label><input id="fw" value="${esc(v.warehouse||"")}"></div><div><label>儲位</label><input id="fl" value="${esc(v.location||"")}"></div><div class="full"><label>備註</label><textarea id="fn">${esc(v.remark||"")}</textarea></div></div><div class="notice">資料會直接寫入 PostgreSQL，主檔與歷史事件分離保存。</div><div class="page-actions"><button class="btn secondary" onclick="closeModal()">取消</button><button class="btn" onclick="saveDevice('${x?.id||""}')">儲存</button></div></div></div>`)}
async function saveDevice(id){const m=document.getElementById("fm").value.trim(),t=document.getElementById("ft").value.trim(),type=document.getElementById("fy").value.trim(),e=document.getElementById("fe").value;if(!/^\d{10}$/.test(m))return alert("料號必須為10位數字。");if(!t||!type||!e)return alert("請完整填寫必填欄位。");const row={material_no:m,taipower_no:t,type,rating_type:document.getElementById("fr").value,warehouse:document.getElementById("fw").value.trim(),location:document.getElementById("fl").value.trim(),entry_date:e,remark:document.getElementById("fn").value.trim()};let r;if(id)r=await db.from("switches").update(row).eq("id",id).select().single();else{row.cycle_start_date=e;row.next_charge_date=addMonths(e,CYCLE);row.state="在庫";r=await db.from("switches").insert(row).select().single()}if(r.error)return alert(r.error.message);closeModal();await refresh()}
async function saveUsage(mode){const id=document.getElementById("uid").value,d=document.getElementById("ud").value,no=document.getElementById("un").value.trim(),note=document.getElementById("unote").value.trim();const rpc=mode==="issue"?"issue_switch":"return_switch";const {error}=await db.rpc(rpc,{p_switch_id:id,p_event_date:d,p_document_no:no||null,p_note:note||null});if(error)return alert(error.message);closeModal();await refresh()}
function openUsage(mode,ids){if(!ids.length)return alert("沒有可操作的設備。");const list=ids.map(id=>devices.find(x=>x.id===id)).filter(Boolean);document.body.insertAdjacentHTML("beforeend",`<div class="modal" id="modal"><div class="modal-box"><div class="modal-head"><h2>${mode==="issue"?"領用／出庫":"退庫／重新入庫"}</h2><button class="close" onclick="closeModal()">×</button></div><div class="form-grid"><div class="full"><label>設備</label><select id="uid">${list.map(x=>`<option value="${x.id}">${esc(x.taipower_no)}｜${esc(x.material_no)}｜${esc(x.type)}</option>`).join("")}</select></div><div><label>${mode==="issue"?"領用日期":"退庫日期"} *</label><input id="ud" type="date" value="${today()}"></div><div><label>單號</label><input id="un"></div><div class="full"><label>備註</label><textarea id="unote"></textarea></div></div><div class="notice ${mode==="return"?"warning":""}">${mode==="issue"?"領用後停止充電倒數。":"退庫後週期起算日＝退庫日，並重新計算6個月。"}</div><div class="page-actions"><button class="btn secondary" onclick="closeModal()">取消</button><button class="btn ${mode==="return"?"success":""}" onclick="saveUsage('${mode}')">確認</button></div></div></div>`)}
function batchSend(){const list=devices.filter(x=>["逾期","即將到期"].includes(st(x).label));if(!list.length)return alert("目前沒有可送檢設備。");document.body.insertAdjacentHTML("beforeend",`<div class="modal" id="modal"><div class="modal-box"><div class="modal-head"><h2>批次送檢</h2><button class="close" onclick="closeModal()">×</button></div><div class="form-grid"><div><label>送檢日期</label><input id="bd" type="date" value="${today()}"></div></div>${table(list,true)}<div class="page-actions"><button class="btn secondary" onclick="closeModal()">取消</button><button class="btn" onclick="batchSave(${JSON.stringify(list.map(x=>x.id))})">確認</button></div></div></div>`)}
async function batchSave(ids){const d=document.getElementById("bd").value;for(const id of ids){const {error}=await db.rpc("send_switch_for_charge",{p_switch_id:id,p_event_date:d,p_transfer_no:null});if(error)return alert(error.message)}closeModal();await refresh()}
async function detail(id){const {data:x,error}=await db.from("switches").select("*").eq("id",id).single();if(error)return alert(error.message);const {data:h}=await db.from("audit_log").select("*").eq("switch_id",id).order("event_at",{ascending:true});const s=st(x);document.body.insertAdjacentHTML("beforeend",`<div class="modal" id="modal"><div class="modal-box"><div class="modal-head"><h2>設備生命週期</h2><button class="close" onclick="closeModal()">×</button></div><div class="form-grid"><div><b>料號</b><br>${esc(x.material_no)}</div><div><b>台電編號</b><br>${esc(x.taipower_no)}</div><div class="full"><b>型式</b><br>${esc(x.type)}</div><div><b>評價</b><br>${esc(x.rating_type)}</div><div><b>狀態</b><br><span class="badge ${s.cls}">${s.label}</span></div><div><b>入帳日期</b><br>${fmt(x.entry_date)}</div><div><b>目前週期起算</b><br>${fmt(x.cycle_start_date)}</div><div><b>下次充電</b><br>${fmt(x.next_charge_date)}</div><div><b>倉庫／儲位</b><br>${esc(x.warehouse||"-")} / ${esc(x.location||"-")}</div></div><div class="page-actions"><button class="btn secondary" onclick="closeModal();openDevice(devices.find(z=>z.id==='${x.id}'))">編輯</button>${x.state==="在庫"&&["逾期","即將到期"].includes(s.label)?`<button class="btn" onclick="closeModal();openCharge('${x.id}')">送檢</button>`:""}${["送檢充電","充電中"].includes(x.state)?`<button class="btn success" onclick="closeModal();completeCharge('${x.id}')">完成充電</button>`:""}${x.state==="領用中"?`<button class="btn success" onclick="closeModal();openUsage('return',['${x.id}'])">退庫</button>`:`<button class="btn danger" onclick="closeModal();openUsage('issue',['${x.id}'])">領用／出庫</button>`}</div><hr><h3>完整生命週期</h3>${timeline(h||[])}</div></div>`)}
function timeline(h){return h?.length?`<div class="timeline">${h.map(v=>`<div class="timeline-item"><div class="timeline-title">${esc(v.event_type)}　${new Date(v.event_at).toLocaleString("zh-TW")}</div><div class="timeline-meta">單號：${esc(v.document_no||"—")}　操作者：${esc(v.actor_email||"system")}</div><div class="timeline-note">${esc(v.note||"")}</div></div>`).join("")}</div>`:'<div class="empty">尚無紀錄</div>'}
function openCharge(id){document.body.insertAdjacentHTML("beforeend",`<div class="modal" id="modal"><div class="modal-box"><div class="modal-head"><h2>送檢充電</h2><button class="close" onclick="closeModal()">×</button></div><div class="form-grid"><div><label>送檢日期</label><input id="cd" type="date" value="${today()}"></div><div><label>充電移撥單號 *</label><input id="cn"></div><div class="full"><label>備註</label><textarea id="cnote"></textarea></div></div><div class="page-actions"><button class="btn secondary" onclick="closeModal()">取消</button><button class="btn" onclick="saveCharge('${id}')">確認</button></div></div></div>`)}
async function saveCharge(id){const d=document.getElementById("cd").value,no=document.getElementById("cn").value.trim(),note=document.getElementById("cnote").value.trim();if(!d||!no)return alert("送檢日期與移撥單號不可空白。");const {error}=await db.rpc("send_switch_for_charge",{p_switch_id:id,p_event_date:d,p_transfer_no:no,p_note:note||null});if(error)return alert(error.message);closeModal();await refresh()}
function completeCharge(id){document.body.insertAdjacentHTML("beforeend",`<div class="modal" id="modal"><div class="modal-box"><div class="modal-head"><h2>登錄充電完成</h2><button class="close" onclick="closeModal()">×</button></div><div class="form-grid"><div><label>實際完成日期 *</label><input id="ccd" type="date" value="${today()}"></div><div><label>移撥單號</label><input id="ccn"></div><div class="full"><label>備註</label><textarea id="ccnote"></textarea></div></div><div class="notice">完成後重新以實際完成日期起算6個月。</div><div class="page-actions"><button class="btn secondary" onclick="closeModal()">取消</button><button class="btn success" onclick="finishCharge('${id}')">確認完成</button></div></div></div>`)}
async function finishCharge(id){const d=document.getElementById("ccd").value,no=document.getElementById("ccn").value.trim(),note=document.getElementById("ccnote").value.trim();const {error}=await db.rpc("complete_switch_charge",{p_switch_id:id,p_event_date:d,p_transfer_no:no||null,p_note:note||null});if(error)return alert(error.message);closeModal();await refresh()}
function closeModal(){document.getElementById("modal")?.remove()}
function modalBackdropClose(e){if(e.target.id==="modal")closeModal()}
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});
document.addEventListener("click",e=>{if(e.target&&e.target.id==="modal")closeModal()});
function csvEsc(v){return `"${String(v??"").replace(/"/g,'""')}"`}
function exportCSV(){download(["料號","型式","台電編號","評價","倉庫","儲位","入帳日期","狀態","週期起算日","上次充電","下次充電","領用日期","退庫日期","領用單號","充電移撥單號"],devices.map(x=>[x.material_no,x.type,x.taipower_no,x.rating_type,x.warehouse,x.location,x.entry_date,x.state,x.cycle_start_date,x.last_charge_date,x.next_charge_date,x.issue_date,x.return_date,x.issue_no,x.transfer_no]),"SwitchCare_設備主檔_"+today()+".csv")}
function report(k){let head=[],rows=[];if(k==="overdue"){head=["料號","台電編號","型式","下次充電","逾期天數"];rows=devices.filter(x=>st(x).label==="逾期").map(x=>[x.material_no,x.taipower_no,x.type,x.next_charge_date,Math.abs(st(x).days)])}else if(k==="soon"){head=["料號","台電編號","型式","下次充電","剩餘天數"];rows=devices.filter(x=>st(x).label==="即將到期").map(x=>[x.material_no,x.taipower_no,x.type,x.next_charge_date,st(x).days])}else{head=["料號","台電編號","型式","領用日期","領用單號"];rows=devices.filter(x=>x.state==="領用中").map(x=>[x.material_no,x.taipower_no,x.type,x.issue_date,x.issue_no])}download(head,rows,"SwitchCare_"+k+"_"+today()+".csv")}
function download(head,rows,name){const q=v=>`"${String(v??"").replace(/"/g,'""')}"`;const csv="\uFEFF"+[head,...rows].map(r=>r.map(q).join(",")).join("\r\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download=name;a.click()}
boot();
