const KEY = "taipower_switch_charging_v1";
const MONTHS = 6;
const REMIND_DAYS = 30;

const seed = [
  {id:crypto.randomUUID(),materialNo:"1102050209",type:"地下四路自動線路開關（24KV 600A 2S2F）",taipowerNo:"A1460480",ratingType:"新品",warehouse:"21M1",location:"A-01",entryDate:"2026-03-10",status:"正常",lastChargeDate:"2026-03-10",nextChargeDate:"2026-09-10",transferNo:"",sendDate:"",completionDate:"",remark:"",history:[]},
  {id:crypto.randomUUID(),materialNo:"1102050209",type:"地下四路自動線路開關（24KV 600A 2S2F）",taipowerNo:"A1460521",ratingType:"舊品",warehouse:"21M1",location:"A-02",entryDate:"2026-02-01",status:"待充電",lastChargeDate:"2026-02-01",nextChargeDate:"2026-08-01",transferNo:"",sendDate:"",completionDate:"",remark:"",history:[]},
  {id:crypto.randomUUID(),materialNo:"1102050301",type:"架空三路自動線路開關（24KV 400A）",taipowerNo:"A1460638",ratingType:"新品",warehouse:"21M6",location:"B-01",entryDate:"2026-05-20",status:"正常",lastChargeDate:"2026-05-20",nextChargeDate:"2026-11-20",transferNo:"",sendDate:"",completionDate:"",remark:"",history:[]}
];

function load(){try{return JSON.parse(localStorage.getItem(KEY))||seed}catch{return seed}}
let data=load();
let currentPage="dashboard";
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function esc(s=""){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]))}
function fmt(d){if(!d)return "-";return new Date(d+"T00:00:00").toLocaleDateString("zh-TW")}
function addMonths(date,months){const d=new Date(date+"T00:00:00");const day=d.getDate();d.setMonth(d.getMonth()+months);if(d.getDate()!==day)d.setDate(0);return d.toISOString().slice(0,10)}
function daysBetween(a,b){return Math.ceil((new Date(b+"T00:00:00")-new Date(a+"T00:00:00"))/86400000)}
function today(){return new Date().toISOString().slice(0,10)}
function calcStatus(x){
  const ref=x.nextChargeDate||addMonths(x.entryDate,MONTHS), days=daysBetween(today(),ref);
  if(x.status==="充電中")return {label:"充電中",cls:"info",days};
  if(x.status==="已開單待送")return {label:"已開單待送",cls:"info",days};
  if(days<0)return {label:"逾期",cls:"danger",days};
  if(days===0)return {label:"待充電",cls:"danger",days};
  if(days<=REMIND_DAYS)return {label:"即將到期",cls:"warning",days};
  return {label:"正常",cls:"normal",days};
}
function syncStatuses(){
  data.forEach(x=>{
    if(!x.history)x.history=[];
    if(!x.nextChargeDate&&x.entryDate)x.nextChargeDate=addMonths(x.entryDate,MONTHS);
    if(!["充電中","已開單待送"].includes(x.status))x.status=calcStatus(x).label;
  }); save();
}
syncStatuses();
function nav(p,t){return `<button class="${currentPage===p?'active':''}" onclick="go('${p}')">${t}</button>`}
function pageTitle(){return {dashboard:"充電管理總覽",switches:"開關資料管理",charging:"充電管理",history:"充電歷史紀錄",reports:"報表中心"}[currentPage]}
function go(p){currentPage=p;layout()}
function layout(){document.getElementById("app").innerHTML=`<div class="app"><aside class="sidebar"><div class="brand">台電自動線路開關<br>充電管理系統<small>Taipower Switch Charging Manager</small></div><nav class="nav">${nav("dashboard","儀表板")}${nav("switches","開關資料")}${nav("charging","充電管理")}${nav("history","充電紀錄")}${nav("reports","報表")}</nav></aside><main class="main"><div class="topbar"><div><h1>${pageTitle()}</h1><span class="muted">6個月定期充電週期管理</span></div><button class="btn" onclick="openAdd()">＋ 新增開關</button></div><div id="content"></div></main></div>`;render()}
function render(){syncStatuses();const c=document.getElementById("content");if(currentPage==="dashboard")dashboard(c);if(currentPage==="switches")switches(c);if(currentPage==="charging")charging(c);if(currentPage==="history")history(c);if(currentPage==="reports")reports(c)}
function card(label,num,cls){return `<div class="card ${cls}"><div class="label">${label}</div><div class="num">${num}</div></div>`}
function dashboard(c){
  const st=data.map(calcStatus),total=data.length,normal=st.filter(x=>x.label==="正常").length,soon=st.filter(x=>x.label==="即將到期").length,due=st.filter(x=>["待充電","逾期"].includes(x.label)).length,active=st.filter(x=>["充電中","已開單待送"].includes(x.label)).length;
  const urgent=data.filter(x=>["逾期","待充電"].includes(calcStatus(x).label)).sort((a,b)=>a.nextChargeDate.localeCompare(b.nextChargeDate));
  const soonList=data.filter(x=>calcStatus(x).label==="即將到期").sort((a,b)=>a.nextChargeDate.localeCompare(b.nextChargeDate));
  c.innerHTML=`<div class="cards">${card("全部設備",total,"")}${card("正常",normal,"success")}${card("30天內到期",soon,"warning")}${card("逾期／待充電",due,"danger")}${card("送充電流程中",active,"")}</div>${urgentPanel(urgent,"逾期／待充電清單")}${urgentPanel(soonList,"30天內即將到期") }<div class="panel"><h2>最近充電紀錄</h2>${historyRows()}</div>`;
}
function urgentPanel(list,title){return `<div class="panel"><h2>${title} <span class="muted">（${list.length}）</span></h2>${list.length?table(list,true):'<div class="empty">目前沒有資料</div>'}</div>`}
function table(list,showDays=false){
 return `<div class="table-wrap"><table><thead><tr><th>料號</th><th>台電編號</th><th>型式</th><th>評價</th><th>入帳日期</th><th>下次充電</th><th>狀態</th><th>移撥單號</th><th>操作</th></tr></thead><tbody>${list.map(x=>{const s=calcStatus(x);return `<tr><td>${esc(x.materialNo)}</td><td>${esc(x.taipowerNo)}</td><td>${esc(x.type)}</td><td>${esc(x.ratingType)}</td><td>${fmt(x.entryDate)}</td><td>${fmt(x.nextChargeDate)}${showDays?`<br><span class="muted">${s.days<0?`逾期 ${Math.abs(s.days)} 天`:s.days===0?"今日到期":`剩 ${s.days} 天`}</span>`:""}</td><td><span class="badge ${s.cls}">${s.label}</span></td><td>${esc(x.transferNo||"-")}</td><td><button class="btn small secondary" onclick="detail('${x.id}')">查看</button></td></tr>`}).join("")}</tbody></table></div>`;
}
function historyRows(){
 const rows=data.flatMap(x=>(x.history||[]).map(h=>({...h,x}))).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8);
 if(!rows.length)return '<div class="empty">尚無充電紀錄</div>';
 return `<div class="table-wrap"><table><thead><tr><th>充電日期</th><th>台電編號</th><th>料號</th><th>移撥單號</th><th>備註</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${fmt(r.date)}</td><td>${esc(r.x.taipowerNo)}</td><td>${esc(r.x.materialNo)}</td><td>${esc(r.transferNo||"-")}</td><td>${esc(r.remark||"-")}</td></tr>`).join("")}</tbody></table></div>`;
}
function switches(c){c.innerHTML=`<div class="panel"><div class="toolbar"><input id="q" placeholder="搜尋料號／台電編號／型式／移撥單號" oninput="filterSwitches()"><select id="filterStatus" onchange="filterSwitches()"><option value="">全部狀態</option><option>正常</option><option>即將到期</option><option>待充電</option><option>逾期</option><option>已開單待送</option><option>充電中</option></select><select id="filterRating" onchange="filterSwitches()"><option value="">全部評價</option><option>新品</option><option>舊品</option></select><button class="btn secondary" onclick="exportCSV()">匯出CSV</button><button class="btn secondary" onclick="importFile()">匯入CSV</button></div><div id="switchTable">${table(data)}</div></div>`}
function filterSwitches(){const q=(document.getElementById("q").value||"").toLowerCase(),fs=document.getElementById("filterStatus").value,fr=document.getElementById("filterRating").value;const list=data.filter(x=>(!q||[x.materialNo,x.taipowerNo,x.type,x.transferNo].join(" ").toLowerCase().includes(q))&&(!fs||calcStatus(x).label===fs)&&(!fr||x.ratingType===fr));document.getElementById("switchTable").innerHTML=table(list)}
function charging(c){const list=data.filter(x=>["即將到期","待充電","逾期","已開單待送","充電中"].includes(calcStatus(x).label)).sort((a,b)=>a.nextChargeDate.localeCompare(b.nextChargeDate));c.innerHTML=`<div class="notice">系統依「入帳日／上次完成充電日＋6個月」自動計算週期。實際完成充電後，下一次週期以完成日重新起算。</div><div class="panel"><div class="toolbar"><button class="btn" onclick="batchOpen()">批次登錄送充電</button></div>${list.length?table(list,true):'<div class="empty">目前沒有需要處理的開關</div>'}</div>`}
function history(c){const rows=data.flatMap(x=>(x.history||[]).map(h=>({...h,x}))).sort((a,b)=>b.date.localeCompare(a.date));c.innerHTML=`<div class="panel"><div class="toolbar"><input id="hq" placeholder="搜尋台電編號／料號／移撥單號" oninput="filterHistory()"></div><div id="historyTable">${historyTable(rows)}</div></div>`}
function historyTable(rows){if(!rows.length)return '<div class="empty">尚無充電紀錄</div>';return `<div class="table-wrap"><table><thead><tr><th>充電日期</th><th>台電編號</th><th>料號</th><th>型式</th><th>移撥單號</th><th>送充電日期</th><th>完成日期</th><th>備註</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${fmt(r.date)}</td><td>${esc(r.x.taipowerNo)}</td><td>${esc(r.x.materialNo)}</td><td>${esc(r.x.type)}</td><td>${esc(r.transferNo||"-")}</td><td>${fmt(r.sendDate)}</td><td>${fmt(r.completionDate)}</td><td>${esc(r.remark||"-")}</td></tr>`).join("")}</tbody></table></div>`}
function filterHistory(){const q=(document.getElementById("hq").value||"").toLowerCase();const rows=data.flatMap(x=>(x.history||[]).map(h=>({...h,x}))).filter(r=>[r.x.materialNo,r.x.taipowerNo,r.transferNo].join(" ").toLowerCase().includes(q)).sort((a,b)=>b.date.localeCompare(a.date));document.getElementById("historyTable").innerHTML=historyTable(rows)}
function reports(c){const overdue=data.filter(x=>["逾期","待充電"].includes(calcStatus(x).label)),soon=data.filter(x=>calcStatus(x).label==="即將到期");c.innerHTML=`<div class="panel"><h2>管理報表</h2><div class="toolbar"><button class="btn" onclick="downloadReport('overdue')">下載逾期／待充電清冊</button><button class="btn secondary" onclick="downloadReport('soon')">下載30天內到期清冊</button><button class="btn secondary" onclick="exportCSV()">下載全部開關資料</button></div><p class="muted">逾期／待充電：${overdue.length} 台；30天內到期：${soon.length} 台。</p></div><div class="panel"><h2>資料完整性檢查</h2>${qualityReport()}</div>`}
function qualityReport(){const issues=[];data.forEach(x=>{if(!/^\d{10}$/.test(x.materialNo))issues.push(`${x.taipowerNo}: 料號不是10碼`);if(!x.taipowerNo)issues.push(`${x.materialNo}: 缺少台電編號`);if(!x.entryDate)issues.push(`${x.taipowerNo}: 缺少入帳日期`);if(x.nextChargeDate&&x.entryDate&&x.nextChargeDate<x.entryDate)issues.push(`${x.taipowerNo}: 下次充電日早於入帳日`)});return issues.length?`<ul>${issues.map(x=>`<li>${esc(x)}</li>`).join("")}</ul>`:'<div class="badge normal">資料檢查正常</div>'}
function openAdd(x=null){const v=x||{materialNo:"",type:"",taipowerNo:"",ratingType:"新品",warehouse:"",location:"",entryDate:today(),remark:""};document.body.insertAdjacentHTML("beforeend",`<div class="modal" id="modal"><div class="modal-box"><div class="modal-head"><h2>${x?"編輯":"新增"}開關資料</h2><button class="close" onclick="closeModal()">×</button></div><div class="form form-grid"><div><label>開關料號（10碼）*</label><input id="f_materialNo" maxlength="10" value="${esc(v.materialNo)}"></div><div><label>台電編號 *</label><input id="f_taipowerNo" value="${esc(v.taipowerNo)}"></div><div class="full"><label>型式 *</label><input id="f_type" value="${esc(v.type)}"></div><div><label>評價類型 *</label><select id="f_ratingType"><option ${v.ratingType==="新品"?"selected":""}>新品</option><option ${v.ratingType==="舊品"?"selected":""}>舊品</option></select></div><div><label>入帳日期 *</label><input id="f_entryDate" type="date" value="${v.entryDate||today()}"></div><div><label>倉庫</label><input id="f_warehouse" value="${esc(v.warehouse||"")}"></div><div><label>儲位</label><input id="f_location" value="${esc(v.location||"")}"></div><div class="full"><label>備註</label><textarea id="f_remark">${esc(v.remark||"")}</textarea></div></div><div class="page-actions"><button class="btn secondary" onclick="closeModal()">取消</button><button class="btn" onclick="saveSwitch('${x?.id||""}')">儲存</button></div></div></div>`)}
function saveSwitch(id){const materialNo=document.getElementById("f_materialNo").value.trim(),taipowerNo=document.getElementById("f_taipowerNo").value.trim(),type=document.getElementById("f_type").value.trim(),entryDate=document.getElementById("f_entryDate").value;if(!/^\d{10}$/.test(materialNo))return alert("開關料號必須為10位數字。 ");if(!taipowerNo||!type||!entryDate)return alert("請完整填寫必填欄位。");if(data.some(z=>z.taipowerNo===taipowerNo&&z.id!==id))return alert("此台電編號已存在，請勿重複建立。");const obj={materialNo,taipowerNo,type,ratingType:document.getElementById("f_ratingType").value,warehouse:document.getElementById("f_warehouse").value.trim(),location:document.getElementById("f_location").value.trim(),entryDate,remark:document.getElementById("f_remark").value.trim()};if(id){const old=data.find(z=>z.id===id);Object.assign(old,obj);if(!old.nextChargeDate)old.nextChargeDate=addMonths(entryDate,MONTHS)}else{data.push({...obj,id:crypto.randomUUID(),status:"正常",lastChargeDate:entryDate,nextChargeDate:addMonths(entryDate,MONTHS),transferNo:"",sendDate:"",completionDate:"",history:[]})}save();closeModal();render()}
function closeModal(){document.getElementById("modal")?.remove()}
function detail(id){const x=data.find(z=>z.id===id),s=calcStatus(x);document.body.insertAdjacentHTML("beforeend",`<div class="modal" id="modal"><div class="modal-box"><div class="modal-head"><h2>開關詳細資料</h2><button class="close" onclick="closeModal()">×</button></div><div class="form-grid"><div><b>料號</b><br>${esc(x.materialNo)}</div><div><b>台電編號</b><br>${esc(x.taipowerNo)}</div><div class="full"><b>型式</b><br>${esc(x.type)}</div><div><b>評價類型</b><br>${esc(x.ratingType)}</div><div><b>入帳日期</b><br>${fmt(x.entryDate)}</div><div><b>上次充電</b><br>${fmt(x.lastChargeDate)}</div><div><b>預計下次充電</b><br>${fmt(x.nextChargeDate)}</div><div><b>目前狀態</b><br><span class="badge ${s.cls}">${s.label}</span></div><div><b>移撥單號</b><br>${esc(x.transferNo||"-")}</div><div><b>倉庫／儲位</b><br>${esc(x.warehouse||"-")} / ${esc(x.location||"-")}</div></div><hr><h3>充電歷史</h3>${x.history?.length?x.history.slice().reverse().map(h=>`<div class="history-item"><strong>${fmt(h.date)}　${esc(h.transferNo||"無移撥單號")}</strong>送充電：${fmt(h.sendDate)}　完成：${fmt(h.completionDate)}<br>${esc(h.remark||"")}</div>`).join(""):'<div class="empty">尚無歷史紀錄</div>'}<div class="page-actions"><button class="btn secondary" onclick="closeModal();openAdd(data.find(z=>z.id===\'${x.id}\'))">編輯</button>${["待充電","逾期","即將到期"].includes(s.label)?`<button class="btn" onclick="closeModal();openCharge('${x.id}')">登錄送充電</button>`:""}${x.status==="已開單待送"||x.status==="充電中"?`<button class="btn success" onclick="closeModal();completeCharge('${x.id}')">登錄充電完成</button>`:""}</div></div></div>`)}
function openCharge(id){const x=data.find(z=>z.id===id);document.body.insertAdjacentHTML("beforeend",`<div class="modal" id="modal"><div class="modal-box"><div class="modal-head"><h2>登錄送充電</h2><button class="close" onclick="closeModal()">×</button></div><div class="form form-grid"><div><label>送充電日期</label><input id="c_send" type="date" value="${today()}"></div><div><label>充電移撥單號 *</label><input id="c_transfer" placeholder="請輸入ERP移撥單號"></div><div class="full"><label>備註</label><textarea id="c_remark"></textarea></div></div><div class="page-actions"><button class="btn secondary" onclick="closeModal()">取消</button><button class="btn" onclick="saveCharge('${id}')">確認送充電</button></div></div></div>`)}
function saveCharge(id){const x=data.find(z=>z.id===id),transfer=document.getElementById("c_transfer").value.trim(),send=document.getElementById("c_send").value;if(!transfer)return alert("請輸入充電移撥單號。");x.transferNo=transfer;x.sendDate=send;x.status="已開單待送";x._pendingRemark=document.getElementById("c_remark").value.trim();save();closeModal();render()}
function completeCharge(id){const x=data.find(z=>z.id===id);document.body.insertAdjacentHTML("beforeend",`<div class="modal" id="modal"><div class="modal-box"><div class="modal-head"><h2>登錄充電完成</h2><button class="close" onclick="closeModal()">×</button></div><div class="form form-grid"><div><label>實際充電完成日期 *</label><input id="cc_date" type="date" value="${today()}"></div><div><label>移撥單號</label><input id="cc_transfer" value="${esc(x.transferNo||"")}"></div><div class="full"><label>充電備註</label><textarea id="cc_remark">${esc(x._pendingRemark||"")}</textarea></div></div><div class="page-actions"><button class="btn secondary" onclick="closeModal()">取消</button><button class="btn success" onclick="finishCharge('${id}')">確認完成</button></div></div></div>`)}
function finishCharge(id){const x=data.find(z=>z.id===id),date=document.getElementById("cc_date").value;if(!date)return alert("請填寫完成日期。");x.history=x.history||[];x.history.push({date,transferNo:document.getElementById("cc_transfer").value.trim()||x.transferNo,sendDate:x.sendDate,completionDate:date,remark:document.getElementById("cc_remark").value.trim()});x.lastChargeDate=date;x.nextChargeDate=addMonths(date,MONTHS);x.status="正常";x.transferNo="";x.sendDate="";x.completionDate=date;x._pendingRemark="";save();closeModal();render()}
function batchOpen(){const list=data.filter(x=>["待充電","逾期"].includes(calcStatus(x).label));if(!list.length)return alert("目前沒有逾期／待充電設備。");const ids=list.map(x=>x.id);document.body.insertAdjacentHTML("beforeend",`<div class="modal" id="modal"><div class="modal-box"><div class="modal-head"><h2>批次登錄送充電</h2><button class="close" onclick="closeModal()">×</button></div><p>將處理 ${list.length} 台開關。</p><div class="form form-grid"><div><label>送充電日期</label><input id="b_send" type="date" value="${today()}"></div><div><label>共同移撥單號（可留空）</label><input id="b_transfer" placeholder="不同單號可於逐筆完成時補登"></div></div><div class="table-wrap">${table(list,true)}</div><div class="page-actions"><button class="btn secondary" onclick="closeModal()">取消</button><button class="btn" onclick="batchSave(${JSON.stringify(ids)})">批次確認</button></div></div></div>`)}
function batchSave(ids){const send=document.getElementById("b_send").value,transfer=document.getElementById("b_transfer").value.trim();ids.forEach(id=>{const x=data.find(z=>z.id===id);x.status="已開單待送";x.sendDate=send;if(transfer)x.transferNo=transfer});save();closeModal();render()}
function csvEscape(v){return `"${String(v??"").replace(/"/g,'""')}"`}
function exportCSV(){const header=["料號","型式","台電編號","評價類型","倉庫","儲位","入帳日期","上次充電日期","預計下次充電日","狀態","移撥單號"],rows=data.map(x=>[x.materialNo,x.type,x.taipowerNo,x.ratingType,x.warehouse,x.location,x.entryDate,x.lastChargeDate,x.nextChargeDate,calcStatus(x).label,x.transferNo]);downloadBlob("\uFEFF"+[header,...rows].map(r=>r.map(csvEscape).join(",")).join("\r\n"),`自動線路開關充電資料_${today()}.csv`)}
function downloadReport(kind){const list=kind==="overdue"?data.filter(x=>["逾期","待充電"].includes(calcStatus(x).label)):data.filter(x=>calcStatus(x).label==="即將到期"),header=["料號","台電編號","型式","評價","入帳日期","預計下次充電日","狀態","移撥單號"],rows=list.map(x=>[x.materialNo,x.taipowerNo,x.type,x.ratingType,x.entryDate,x.nextChargeDate,calcStatus(x).label,x.transferNo]);downloadBlob("\uFEFF"+[header,...rows].map(r=>r.map(csvEscape).join(",")).join("\r\n"),`充電_${kind}_${today()}.csv`)}
function downloadBlob(text,name){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:"text/csv;charset=utf-8"}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importFile(){const input=document.createElement("input");input.type="file";input.accept=".csv,text/csv";input.onchange=async()=>{const f=input.files[0];if(!f)return;const rows=parseCSV((await f.text()).replace(/^\uFEFF/,""));let ok=0,fail=0,msg=[];rows.slice(1).forEach((r,i)=>{const materialNo=(r[0]||"").trim(),type=(r[1]||"").trim(),taipowerNo=(r[2]||"").trim(),ratingType=(r[3]||"新品").trim(),warehouse=(r[4]||"").trim(),location=(r[5]||"").trim(),entryDate=(r[6]||"").trim();if(!/^\d{10}$/.test(materialNo)||!taipowerNo||!/^\d{4}-\d{2}-\d{2}$/.test(entryDate)){fail++;msg.push(`第${i+2}列：料號須10碼、台電編號與有效入帳日期不可空白`);return}if(data.some(x=>x.taipowerNo===taipowerNo)){fail++;msg.push(`第${i+2}列：台電編號 ${taipowerNo} 已存在`);return}data.push({id:crypto.randomUUID(),materialNo,type,taipowerNo,ratingType,warehouse,location,entryDate,nextChargeDate:addMonths(entryDate,MONTHS),lastChargeDate:entryDate,status:"正常",transferNo:"",sendDate:"",completionDate:"",remark:"",history:[]});ok++});save();syncStatuses();alert(`匯入完成\n成功：${ok} 筆\n失敗：${fail} 筆${msg.length?"\n\n"+msg.slice(0,8).join("\n"):""}`);render()};input.click()}
function parseCSV(t){return t.split(/\r?\n/).filter(Boolean).map(line=>{const a=[];let cur="",q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'&&line[i+1]==='"'){cur+='"';i++;continue}if(ch==='"'){q=!q;continue}if(ch===','&&!q){a.push(cur);cur="";continue}cur+=ch}a.push(cur);return a})}
layout();
